as yet unclassified
additionsToViewerCategories
	^ # ((blob (
(slot source '' Player readWrite Player getSource Player setSource:)
(slot trackedColor '' Color readWrite Player getTrackedColor Player setTrackedColor:)
(slot hueMargin '' Number readWrite Player getHueMargin Player setHueMargin:)
(slot saturationMargin '' Number readWrite Player getSaturationMargin Player setSaturationMargin:)
(slot brightnessMargin '' Number readWrite Player getBrightnessMargin Player setBrightnessMargin:)
(slot blobX '' Number readOnly Player getBlobX unused unused)
(slot blobY '' Number readOnly Player getBlobY unused unused)
(slot blobWidth '' Number readOnly Player getBlobWidth unused unused)
(slot blobHeight '' Number readOnly Player getBlobHeight unused unused)
(slot blobFound '' Boolean readOnly Player getBlobFound unused unused)
(slot fps '' Number readOnly Player getFps unused unused)
)))
